export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "surface-container-highest": "#252626",
          "on-tertiary-fixed-variant": "#576b5b",
          "on-tertiary-fixed": "#3b4e40",
          "surface-container-low": "#131313",
          "on-primary-container": "#d4d0c8",
          "on-surface": "#e7e5e5",
          "surface-dim": "#0e0e0e",
          "on-background": "#e7e5e5",
          "surface-tint": "#cac6be",
          "outline": "#757575",
          "tertiary-fixed-dim": "#d5ebd7",
          "error": "#ee7d77",
          "surface-container-lowest": "#000000",
          "on-surface-variant": "#acabab",
          "surface": "#0e0e0e",
          "inverse-surface": "#fcf9f8",
          "tertiary-fixed": "#e4f9e5",
          "on-error": "#490106",
          "surface-variant": "#252626",
          "surface-container": "#191a1a",
          "surface-bright": "#2b2c2c",
          "secondary": "#9b9ea7",
          "secondary-fixed-dim": "#d1d4de",
          "tertiary-container": "#dbf1dd",
          "inverse-on-surface": "#565555",
          "secondary-fixed": "#e0e2ed",
          "background": "#0e0e0e",
          "on-secondary": "#1c2028",
          "on-primary-fixed": "#413f3a",
          "on-error-container": "#ff9993",
          "secondary-dim": "#9b9ea7",
          "primary-container": "#494741",
          "primary-fixed-dim": "#d9d4cc",
          "on-primary-fixed-variant": "#5e5b55",
          "on-secondary-container": "#bcbfc9",
          "secondary-container": "#383b44",
          "on-primary": "#42403a",
          "on-secondary-fixed": "#3c3f48",
          "inverse-primary": "#615f59",
          "tertiary": "#e9ffeb",
          "on-tertiary-container": "#485b4c",
          "outline-variant": "#474848",
          "error-dim": "#bb5551",
          "tertiary-dim": "#dbf1dd",
          "primary-dim": "#bcb8b1",
          "error-container": "#7f2927",
          "primary-fixed": "#e7e2da",
          "primary": "#cac6be",
          "on-tertiary": "#506454",
          "surface-container-high": "#1f2020",
          "on-secondary-fixed-variant": "#585b64"
      },
      "borderRadius": {
          "DEFAULT": "0px",
          "lg": "0px",
          "xl": "0px",
          "full": "9999px"
      },
      "fontFamily": {
          "headline": ["Noto Serif", "serif"],
          "body": ["Manrope", "sans-serif"],
          "label": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
